import { Inter } from 'next/font/google'
import './globals.css'
import Footer from './components/Footer/Footer'
import AnimatedCursor from 'react-animated-cursor'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <CustomNavbar></CustomNavbar> */}
        <AnimatedCursor
          color='0,135,248'
          innerSize={8}
          outerSize={32}
        />
        {children}
        <Footer></Footer>
      </body>
    </html>
  )
}
